"use client";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { createResourceLinkAction, deleteResourceLinkAction, updateResourceLinkAction } from "@/app/actions";
import { detectResourceType } from "@/lib/resources";

export const resourceTypes = { google_docs:["Google Docs","DOC"],google_slides:["Google Slides","SLD"],google_sheets:["Google Sheets","SHT"],google_drive:["Google Drive","DRV"],youtube:["YouTube","▶"],notebooklm:["NotebookLM","AI"],pdf:["PDF","PDF"],notes:["Notes","▤"],video:["Video","▶"],textbook:["Textbook","▥"],test:["Previous test","✓"],website:["Website","↗"] };

export default function ResourceLibrary({ resources, subjects, folders }) {
  const router=useRouter(); const [query,setQuery]=useState(""); const [type,setType]=useState("all"); const [sort,setSort]=useState("newest"); const [openModules,setOpenModules]=useState(()=>new Set()); const [openUnits,setOpenUnits]=useState(()=>new Set()); const [editing,setEditing]=useState(null); const [drawerOpen,setDrawerOpen]=useState(false); const [notice,setNotice]=useState(""); const [pending,startTransition]=useTransition();
  const filtering=Boolean(query.trim())||type!=="all";
  const visible=useMemo(()=>{ const needle=query.trim().toLowerCase(); const result=resources.filter(item=>(type==="all"||item.type===type)&&(!needle||[item.title,item.description,item.url,resourceTypes[item.type]?.[0],item.subject_name,item.folder_name].some(value=>String(value||"").toLowerCase().includes(needle)))); return [...result].sort(sort==="name"?(a,b)=>a.title.localeCompare(b.title):sort==="oldest"?(a,b)=>String(a.created_at).localeCompare(String(b.created_at)):(a,b)=>String(b.created_at).localeCompare(String(a.created_at))); },[query,resources,sort,type]);
  const toggle=(setter,id)=>setter(current=>{const next=new Set(current);next.has(String(id))?next.delete(String(id)):next.add(String(id));return next;});
  const resourcesForUnit=id=>visible.filter(item=>String(item.folder_id)===String(id)); const moduleResources=id=>visible.filter(item=>String(item.subject_id)===String(id)&&!item.folder_id);
  const openCreate=()=>{setEditing(null);setDrawerOpen(true);setNotice("");}; const openEdit=resource=>{setEditing(resource);setDrawerOpen(true);setNotice("");};
  const run=(action,data,success,close=true)=>startTransition(async()=>{try{await action(data);const subject=data.get("subjectId"),folder=data.get("folderId");if(subject)setOpenModules(current=>new Set(current).add(String(subject)));if(folder)setOpenUnits(current=>new Set(current).add(String(folder)));setNotice(success);if(close)setDrawerOpen(false);router.refresh();}catch(error){setNotice(error?.message||"That resource could not be saved.");}});
  const remove=resource=>{if(!window.confirm(`Remove ${resource.title} from Snoozelet? The original external file will not be deleted.`))return;const data=new FormData();data.set("resourceId",resource.id);data.set("subjectId",resource.subject_id||"");data.set("folderId",resource.folder_id||"");run(deleteResourceLinkAction,data,`${resource.title} removed.`,false);};
  const copyLink=async resource=>{await navigator.clipboard.writeText(resource.url);setNotice("Link copied.");};
  const ResourceActions=({resource})=><details className="file-actions"><summary aria-label={`Actions for ${resource.title}`}>•••</summary><div><a href={resource.url} target="_blank" rel="noopener noreferrer">Open resource</a><button type="button" onClick={()=>openEdit(resource)}>Edit</button><button type="button" onClick={()=>openEdit(resource)}>Move</button><button type="button" onClick={()=>copyLink(resource)}>Copy link</button><button className="danger-text" type="button" onClick={()=>remove(resource)}>Remove</button></div></details>;
  const ResourceRow=({resource})=><div className="file-row resource-file"><a className="file-open" href={resource.url} target="_blank" rel="noopener noreferrer"><span className="resource-kind" aria-hidden="true">{resourceTypes[resource.type]?.[1]||"↗"}</span><span><strong>{resource.title}</strong><small>{resourceTypes[resource.type]?.[0]||resource.type}{resource.description?` · ${resource.description}`:""}</small></span></a><span>{resourceTypes[resource.type]?.[0]||resource.type}</span><span><a href={resource.url} target="_blank" rel="noopener noreferrer">Open resource ↗</a></span><ResourceActions resource={resource}/></div>;
  return <section className="file-library resource-file-library"><header className="file-toolbar"><div className="file-breadcrumb"><span className="file-home-icon">R</span><div><strong>Study resources</strong><small>{resources.length} resources</small></div></div><div className="file-toolbar-actions"><label className="file-search"><span>⌕</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search resources" aria-label="Search resources"/></label><select value={type} onChange={e=>setType(e.target.value)} aria-label="Filter by resource type"><option value="all">All types</option>{Object.entries(resourceTypes).map(([value,[label]])=><option value={value} key={value}>{label}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort resources"><option value="newest">Newest added</option><option value="oldest">Oldest added</option><option value="name">Name A–Z</option></select><button className="button primary" type="button" onClick={openCreate}>＋ Add resource</button></div></header>
  {notice?<p className="library-notice" role="status">{pending?"Saving…":notice}</p>:null}<div className="file-column-head"><span>Name</span><span>Type</span><span>Open</span><span>Actions</span></div><div className="file-tree">
  {subjects.filter(subject=>!filtering||visible.some(item=>String(item.subject_id)===String(subject.id))).map(subject=>{const units=folders.filter(folder=>String(folder.subject_id)===String(subject.id)),total=visible.filter(item=>String(item.subject_id)===String(subject.id)),direct=moduleResources(subject.id),moduleOpen=filtering||openModules.has(String(subject.id)),unitCount=units.filter(unit=>resourcesForUnit(unit.id).length).length;return <section className="file-folder" key={subject.id}><div className="file-row module-row"><button className="file-open" type="button" aria-expanded={moduleOpen} onClick={()=>toggle(setOpenModules,subject.id)}><span className="chevron">{moduleOpen?"⌄":"›"}</span><span className="folder-icon">▰</span><span><strong>{subject.name}</strong><small>{unitCount} Study Units containing resources</small></span></button><span>{total.length} resources</span><span>Module</span><span/></div>{moduleOpen?<div className="file-children">{direct.length?<div className="unit-folder module-resource-group"><div className="file-row unit-row"><div className="file-open"><span className="chevron"/><span className="folder-icon secondary">▰</span><span><strong>Module resources</strong><small>{direct.length} resources</small></span></div><span>{direct.length} resources</span><span>Module</span><span/></div><div className="file-decks">{direct.map(resource=><ResourceRow resource={resource} key={resource.id}/>)}</div></div>:null}{units.filter(unit=>!filtering||resourcesForUnit(unit.id).length).map(unit=>{const contained=resourcesForUnit(unit.id),unitOpen=filtering||openUnits.has(String(unit.id));return <div className="unit-folder" key={unit.id}><div className="file-row unit-row"><button className="file-open" type="button" aria-expanded={unitOpen} onClick={()=>toggle(setOpenUnits,unit.id)}><span className="chevron">{unitOpen?"⌄":"›"}</span><span className="folder-icon secondary">▰</span><span><strong>{unit.name}</strong><small>Study Unit</small></span></button><span>{contained.length} resources</span><span>Study Unit</span><span/></div>{unitOpen?<div className="file-decks">{contained.length?contained.map(resource=><ResourceRow resource={resource} key={resource.id}/>):<div className="empty-folder"><span>No resources in this Study Unit</span></div>}</div>:null}</div>;})}</div>:null}</section>;})}
  {visible.some(item=>!item.subject_id)?<section className="loose-files"><div className="file-section-label">Unassigned resources</div>{visible.filter(item=>!item.subject_id).map(resource=><ResourceRow resource={resource} key={resource.id}/>)}</section>:null}
  {!visible.length?<div className="workspace-empty"><strong>{filtering?"No resources match":"No resources yet"}</strong><p>{filtering?"Try another search or filter.":"Add a document, video, PDF, or website to begin."}</p><button className="button primary" type="button" onClick={openCreate}>Add resource</button></div>:null}</div>
  {drawerOpen?<ResourceEditor resource={editing} resources={resources} subjects={subjects} folders={folders} pending={pending} onClose={()=>setDrawerOpen(false)} onSubmit={data=>run(editing?updateResourceLinkAction:createResourceLinkAction,data,editing?"Resource updated.":"Resource saved.")}/>:null}</section>;
}

function ResourceEditor({resource,resources,subjects,folders,pending,onClose,onSubmit}) {
  const [title,setTitle]=useState(resource?.title||""),[url,setUrl]=useState(resource?.url||""),[subjectId,setSubjectId]=useState(String(resource?.subject_id||"")),[folderId,setFolderId]=useState(String(resource?.folder_id||"")),[type,setType]=useState(resource?.type||"website"),[manualType,setManualType]=useState(Boolean(resource)),[error,setError]=useState(""); const availableFolders=folders.filter(item=>String(item.subject_id)===subjectId);
  const changeUrl=value=>{setUrl(value);if(!manualType){const detected=detectResourceType(value);if(detected)setType(detected);}};
  function submit(event){event.preventDefault();setError("");let parsed;try{parsed=new URL(url);}catch{setError("Enter a complete URL beginning with http:// or https://.");return;}if(!["http:","https:"].includes(parsed.protocol)){setError("Resource links must begin with http:// or https://.");return;}if(!title.trim()){setError("Enter a meaningful resource title.");return;}if(!subjectId){setError("Choose a Module.");return;}if(resources.some(item=>String(item.id)!==String(resource?.id)&&item.url===parsed.href)){setError("This exact resource link is already saved.");return;}onSubmit(new FormData(event.currentTarget));}
  return <div className="resource-modal" role="dialog" aria-modal="true" aria-labelledby="resource-editor-title"><button className="resource-modal-backdrop" type="button" onClick={onClose} aria-label="Close resource editor"/><section><header><div><p className="eyebrow">{resource?"Edit resource":"New resource"}</p><h2 id="resource-editor-title">{resource?"Update or move resource":"Add a study resource"}</h2></div><button type="button" onClick={onClose} aria-label="Close">×</button></header><form onSubmit={submit} noValidate>{resource?<input type="hidden" name="resourceId" value={resource.id}/>:null}<label>Resource title<input name="title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="CPU Scheduling Lecture Notes" maxLength="120" required/></label><label>URL<input name="url" type="url" value={url} onChange={e=>changeUrl(e.target.value)} placeholder="https://…" required/></label><div className="resource-editor-grid"><label>Module<select name="subjectId" value={subjectId} onChange={e=>{setSubjectId(e.target.value);setFolderId("");}} required><option value="">Choose Module</option>{subjects.map(subject=><option value={subject.id} key={subject.id}>{subject.name}</option>)}</select></label><label>Study Unit<select name="folderId" value={folderId} onChange={e=>setFolderId(e.target.value)} disabled={!subjectId}><option value="">Whole Module</option>{availableFolders.map(folder=><option value={folder.id} key={folder.id}>{folder.name}</option>)}</select></label></div><label>Resource type<select name="type" value={type} onChange={e=>{setType(e.target.value);setManualType(true);}}>{Object.entries(resourceTypes).map(([value,[label]])=><option value={value} key={value}>{label}</option>)}</select><small>{detectResourceType(url)?`Suggested from URL: ${resourceTypes[detectResourceType(url)]?.[0]}`:"Paste a supported URL to detect its provider."}</small></label><label>Description <span className="optional">Optional</span><textarea name="description" defaultValue={resource?.description||""} rows="4" maxLength="300"/></label>{error?<p className="form-error" role="alert">{error}</p>:null}<footer><button className="button" type="button" onClick={onClose}>Cancel</button><button className="button primary" type="submit" disabled={pending}>{pending?"Saving…":"Save resource"}</button></footer></form></section></div>;
}
