"use client";
import { useMemo, useState } from "react";
import { createResourceLinkAction, deleteResourceLinkAction, updateResourceLinkAction } from "@/app/actions";
import PendingForm from "@/components/PendingForm";

const labels = { notes: "Google Docs / notes", notebooklm: "NotebookLM", video: "Video", textbook: "Textbook / PDF", website: "Website", test: "Previous test" };

export default function ResourceLibrary({ resources, subjects, folders }) {
  const [query, setQuery] = useState("");
  const [subjectId, setSubjectId] = useState("");
  const visibleFolders = folders.filter((folder) => !subjectId || String(folder.subject_id) === subjectId);
  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return needle ? resources.filter((item) => [item.title,item.description,item.subject_name,item.folder_name,item.type].some((value) => String(value || "").toLowerCase().includes(needle))) : resources; }, [query, resources]);
  return <div className="resource-library">
    <section className="resource-library-toolbar"><div><p className="eyebrow">Your library</p><h2>{resources.length} saved {resources.length === 1 ? "link" : "links"}</h2></div><label><span>Search</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search notes and resources"/></label></section>
    {filtered.length ? <div className="resource-grid resource-library-grid">{filtered.map((resource) => <article className="resource-card" key={resource.id}><span className="resource-kind">{resource.type === "notes" ? "DOC" : resource.type === "notebooklm" ? "AI" : "LINK"}</span><div><small>{[resource.subject_name,resource.folder_name].filter(Boolean).join(" / ") || "Resource"}</small><h3>{resource.title}</h3><p>{resource.description || labels[resource.type] || "External study resource"}</p><a href={resource.url} target="_blank" rel="noreferrer">Open {labels[resource.type] || "resource"} ↗</a><details className="resource-edit"><summary>Edit details</summary><form action={updateResourceLinkAction} className="form-stack"><input type="hidden" name="resourceId" value={resource.id}/><input type="hidden" name="subjectId" value={resource.subject_id || ""}/><input type="hidden" name="folderId" value={resource.folder_id || ""}/><label>Title<input name="title" defaultValue={resource.title} required/></label><label>URL<input name="url" type="url" defaultValue={resource.url} required/></label><label>Type<select name="type" defaultValue={resource.type}>{Object.entries(labels).map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Description<input name="description" defaultValue={resource.description || ""}/></label><button className="button" type="submit">Save changes</button></form></details></div><form action={deleteResourceLinkAction}><input type="hidden" name="resourceId" value={resource.id}/><input type="hidden" name="subjectId" value={resource.subject_id || ""}/><input type="hidden" name="folderId" value={resource.folder_id || ""}/><button type="submit" aria-label={`Delete ${resource.title}`}>×</button></form></article>)}</div> : <div className="workspace-empty"><strong>No matching links</strong><p>Add your first Google Doc or change the search.</p></div>}
    <section className="resource-add-panel" id="add-resource"><div><p className="eyebrow">Add a link</p><h2>Connect existing notes</h2><p>Snoozelet stores the link and its place in your course. Your actual document stays in Google Docs or its original service.</p></div><PendingForm action={createResourceLinkAction} submitLabel="Save link" pendingLabel="Saving locally…"><label>Title<input name="title" maxLength="120" placeholder="Week 4 lecture notes" required/></label><label>URL<input name="url" type="url" placeholder="https://docs.google.com/…" required/></label><div className="note-context-fields"><label>Module<select name="subjectId" value={subjectId} onChange={(event) => setSubjectId(event.target.value)} required><option value="">Choose Module</option>{subjects.map((subject) => <option value={subject.id} key={subject.id}>{subject.name}</option>)}</select></label><label>Study Unit<select name="folderId" defaultValue=""><option value="">Whole Module</option>{visibleFolders.map((folder) => <option value={folder.id} key={folder.id}>{folder.name}</option>)}</select></label><label>Type<select name="type" defaultValue="notes">{Object.entries(labels).map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select></label></div><label>Description<input name="description" maxLength="300" placeholder="Optional reminder of what this contains"/></label><button className="button primary" type="submit">Save link locally</button></PendingForm></section>
  </div>;
}
